# Generated by Django 3.2.7 on 2022-02-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_products_currency'),
        ('shop', '0002_auto_20220209_1828'),
    ]

    operations = [
    ]
