<<<<<<< HEAD
# Generated by Django 3.2.7 on 2022-02-09 06:31
=======
# Generated by Django 3.2.7 on 2022-02-09 12:19
>>>>>>> test

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(help_text='Enter product name', max_length=250)),
<<<<<<< HEAD
                ('upload_Product_Image', models.ImageField(default='default.jpg', upload_to='staticfiles/images')),
=======
                ('upload_Product_Image', models.ImageField(default='default.jpg', upload_to='')),
>>>>>>> test
                ('product_Description', models.CharField(default='', max_length=200)),
                ('weight', models.CharField(blank=True, default='g/kg/lb', max_length=10)),
                ('size', models.CharField(blank=True, choices=[('X', 'Small'), ('XX', 'Large'), ('XXL', 'Extra large')], default='X', max_length=5)),
                ('stock', models.IntegerField(default='Choose total number of goods available')),
                ('currency', models.CharField(choices=[('Naira Token', 'NGNT'), ('Dollar', 'USD')], default=0.0, max_length=11)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='', help_text='Your store name', max_length=250)),
<<<<<<< HEAD
=======
                ('logo', models.ImageField(default='default.jpg', upload_to='')),
                ('cover_Art', models.ImageField(default='default.jpg', upload_to='')),
>>>>>>> test
                ('about', models.TextField(default='', help_text='Give a catchy description of your store', max_length=1000)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', help_text='Your email name', max_length=250)),
                ('location', models.CharField(default='', help_text='Enter your store location', max_length=250)),
            ],
        ),
    ]
