# Generated by Django 3.2.7 on 2022-01-25 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(default='', help_text='Enter product name', max_length=250)),
                ('image', models.ImageField(default='default.jpg', upload_to='static/images/products/')),
                ('description', models.CharField(default='', max_length=200)),
                ('weight', models.CharField(blank=True, default='g/kg', max_length=10)),
                ('stock', models.IntegerField(default=5)),
                ('currency', models.CharField(choices=[('Nigerian Naira', 'NGN')], default=0.0, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.category')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='', help_text='Your store name', max_length=250)),
                ('email', models.EmailField(default='', help_text='Your email name', max_length=250)),
                ('phone', models.IntegerField(default=50)),
                ('location', models.CharField(default='', help_text='Enter your store location', max_length=250)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.products')),
            ],
        ),
    ]
