# Generated by Django 3.2.7 on 2022-06-13 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='', help_text='Your store name', max_length=250)),
                ('logo', models.ImageField(upload_to='staticfiles/images')),
                ('about', models.TextField(default='', help_text='Give a catchy description of your store', max_length=1000)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', help_text='Your email name', max_length=250)),
                ('location', models.CharField(default='', help_text='Enter your store location', max_length=250)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='', help_text='Describe your services ', max_length=250)),
                ('service_description', models.TextField(default='', max_length=1000)),
                ('payment_method', models.CharField(choices=[('pp', 'Pay per Hour'), ('p', 'Partition'), ('FR', 'Flat Rate')], default='', max_length=250)),
                ('service', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stores.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Product_name', models.CharField(default='', max_length=100)),
                ('upload_Product_Image', models.ImageField(default='default.jpg', upload_to='staticfiles/products')),
                ('price', models.IntegerField()),
                ('size', models.CharField(blank=True, choices=[('X', 'Small'), ('XX', 'Large'), ('XXL', 'Extra large')], default='X', max_length=5)),
                ('stock', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.category')),
                ('vendor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stores.vendor')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='products')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stores.products')),
            ],
        ),
    ]
