# Generated by Django 3.2.7 on 2022-02-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(upload_to='staticfiles/products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='upload_Product_Image',
            field=models.ImageField(default='default.jpg', upload_to='staticfiles/products'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(upload_to='staticfiles/profilepic'),
        ),
    ]
