# Generated by Django 3.2.7 on 2022-06-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='brand_name',
            new_name='store_name',
        ),
    ]
