# Generated by Django 3.2.7 on 2022-01-29 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='description',
            new_name='product_Description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, choices=[('X', 'Small'), ('XX', 'Large'), ('XXL', 'Extra large')], default='X', max_length=5),
        ),
        migrations.AddField(
            model_name='products',
            name='upload_Product_Image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
        migrations.AddField(
            model_name='store',
            name='about',
            field=models.TextField(default='', help_text='Give a catchy description of your store', max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='currency',
            field=models.CharField(choices=[('Naira Token', 'NGNT'), ('Dollar', 'USD')], default=0.0, help_text='The Naira Token is a stablecoin tied to the value of the naira, in other words NGN200 = NGNT200', max_length=11),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_Name',
            field=models.CharField(help_text='Enter product name', max_length=250),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default='Choose total number of goods available'),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.CharField(blank=True, default='g/kg/lb', max_length=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
