# Generated by Django 3.2.7 on 2022-03-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_tag',
        ),
    ]
