# Generated by Django 3.2.7 on 2022-02-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='', help_text='Describe your services ', max_length=250)),
                ('service_description', models.TextField(default='', max_length=1000)),
                ('payment_method', models.CharField(choices=[('pp', 'Pay per Hour'), ('p', 'Partition'), ('FR', 'Flat Rate')], default='', max_length=250)),
            ],
        ),
    ]
