# Generated by Django 3.2.7 on 2022-02-16 02:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.FileField(upload_to='staticfiles/images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(upload_to='staticfiles/images'),
        ),
    ]
