# Generated by Django 3.2.7 on 2022-03-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20220318_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='upload_Product_Image',
            field=models.ImageField(default='default.jpg', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(upload_to='profilepic'),
        ),
    ]
