# Generated by Django 3.2.7 on 2022-02-23 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_products_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stores.vendor'),
        ),
    ]
