# Generated by Django 3.2.7 on 2022-03-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20220303_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='imageUrl',
        ),
    ]
