# Generated by Django 3.2.7 on 2022-02-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_products_upload_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='upload_Product_Image',
            field=models.ImageField(default='default.jpg', upload_to='staticfiles/images'),
        ),
    ]
