# Generated by Django 3.2.7 on 2022-03-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_remove_products_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='Product_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_tag',
        ),
    ]
