# Generated by Django 3.2.7 on 2022-02-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_products_upload_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Vendor',
        ),
    ]
