# Generated by Django 3.2.7 on 2022-02-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_rename_store_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='currency',
            field=models.CharField(default=0.0, max_length=11),
        ),
        migrations.AlterField(
            model_name='products',
            name='upload_Product_Image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stores.products')),
            ],
        ),
    ]
