# Generated by Django 3.2.7 on 2022-02-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20220209_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.RemoveField(
            model_name='products',
            name='currency',
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
